name: saint-daniels
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/saint-daniels
  build_command: npm run build
  run_command: npm start
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: / 